using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace shelbysBible.Support
{
    public enum BibleBooksEnum
    {
        genesis = 1,
        exodus,
        leviticus,
        numbers,
        deuteronomy,
        joshua,
        judges,
        ruth,
        samuel1,
        samuel2,
        kings1,
        kings2,
        chronicles1,
        chronicles2,
        ezra,
        nehemiah,
        esther,
        job,
        psalm,
        proverbs,
        ecclesiastes,
        songofsoloman,
        isaiah,
        jeremiah,
        lamentations,
        ezekiel,
        daniel,      
        hosea,       
        joel,        
        amos,        
        obadiah,     
        jonah,       
        micah,       
        nahum,       
        habakkuk,    
        zephaniah,   
        haggai,      
        zechariah,   
        malachi,     
        // New Testament
        matthew,     
        mark,        
        luke,        
        john,        
        acts,        
        romans,      
        corinthians1,
        corinthians2,
        galatians,   
        ephesians,   
        philippians, 
        colossians,  
        thessalonians1,
        thessalonians2,
        timothy1,    
        timothy2,    
        titus,      
        philemon,    
        hebrews,     
        james,       
        peter1,      
        peter2,      
        john1,       
        john2,       
        john3,       
        jude,        
        revelation  
    }
}